version: '3.3'
services:
  api:
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/app/node_modules
    ports:
      - 8080:8080
    env_file:
      - .env
    command: 
      - /bin/sh
      - -c
      - npm run dev

  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: